spring:
  datasource:
    url: jdbc:mysql://localhost/ecommerce?serverTimezone=UTC
    username: root
    password: 2771999
    initialization-mode: always  #never
  jpa:
    show-sql: false #true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
    mode: HTML5