spring:
  datasource:
    url: jdbc:mysql://localhost/modulo_correo?serverTimezone=UTC
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
server:
  port : 8083